import random
import datetime


# =============================================================================
# Meter Record Generator
# =============================================================================
# METER Table Schema (per readme.md ER diagram):
#   meter_id     PK  X(7)  - Generated by COBOL (MTR-###)
#   cust_id      FK  X(9)  - Reference to CUSTOMER.cust_id
#   install_date     X(10) - YYYY-MM-DD format
#   status           X(1)  - A=Active, I=Inactive, R=Replaced
# =============================================================================


def format_field(value, length):
    """Format value to fixed length, left-justified."""
    return str(value).ljust(length)[:length]


def generate_meter_record(index):
    """Generate a meter record without meter_id (generated by COBOL)."""
    
    # -------------------------------------------------------------------------
    # Generate Customer ID (FK) - matches format from elect001.txt
    # Format: XXYY + 4-digit sequence (like AR01-0001)
    # -------------------------------------------------------------------------
    area_prefix = random.choice(["AR", "BR", "CR", "DR", "ER", "FR"])
    area_num = random.randint(1, 9)
    area_code = f"{area_prefix}{area_num:02d}"
    
    # Customer ID: AREA + 4-digit sequence
    cust_seq = 1001 + (index % 999)
    cust_id = f"{area_code}-{cust_seq:04d}"
    
    # -------------------------------------------------------------------------
    # Installation date: random date in past 2 years
    # -------------------------------------------------------------------------
    install_date = (datetime.date.today() - 
                    datetime.timedelta(days=random.randint(0, 730))).strftime("%Y-%m-%d")
    
    # -------------------------------------------------------------------------
    # Status: A=Active, I=Inactive, R=Replaced
    # -------------------------------------------------------------------------
    status = random.choice(["A", "I", "R"])
    
    # -------------------------------------------------------------------------
    # Build record
    # -------------------------------------------------------------------------
    record = (
        format_field(cust_id, 9) +          # 9 bytes - FK to CUSTOMER
        " " +                                # 1 space for readability
        format_field(install_date, 10) +    # 10 bytes - YYYY-MM-DD
        " " +                                # 1 space for readability
        format_field(status, 1)             # 1 byte - A/I/R
    )
    
    return record


# =============================================================================
# File Generation
# =============================================================================

if __name__ == "__main__":
    
    with open("meter_input_200.txt", "w") as f:
        for i in range(200):
            f.write(generate_meter_record(i) + "\n")
    
    print("=" * 60)
    print("Generated meter_input_200.txt")
    print("=" * 60)
    print(f"Record size: 22 bytes (with 2 spaces for readability)")
    print(f"  - CUST_ID:       9 bytes")
    print(f"  - Space:         1 byte")
    print(f"  - INSTALL_DATE:  10 bytes")
    print(f"  - Space:         1 byte")
    print(f"  - STATUS:        1 byte")
    print("=" * 60)
    print("Meter ID (MTR-###) will be generated by COBOL program")
    print("=" * 60)
